using System;
using System.IO;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace ArmaServerManager.Core;

public class ConfigManager
{
    private readonly string _configsPath;
    private readonly ILogger _logger;

    public ConfigManager(string configsPath, ILogger logger)
    {
        _configsPath = string.IsNullOrEmpty(configsPath) ? Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Data", "Configs") : configsPath;
        _logger = logger;
        Directory.CreateDirectory(_configsPath);
    }

    public async Task SaveConfigAsync(ArmaServer server)
    {
        try
        {
            var configFile = Path.Combine(_configsPath, $"{server.Name}.json");
            var json = JsonSerializer.Serialize(server, new JsonSerializerOptions { WriteIndented = true });
            await File.WriteAllTextAsync(configFile, json).ConfigureAwait(false);
            
            await GenerateServerCfgAsync(server).ConfigureAwait(false);
            _logger.LogInformation("Server config saved: {ServerName}", server.Name);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to save config for server: {ServerName}", server.Name);
            throw;
        }
    }

    public async Task<ArmaServer?> LoadConfigAsync(string serverName)
    {
        try
        {
            var configFile = Path.Combine(_configsPath, $"{serverName}.json");
            if (!File.Exists(configFile)) return null;
            
            var json = await File.ReadAllTextAsync(configFile).ConfigureAwait(false);
            return JsonSerializer.Deserialize<ArmaServer>(json);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to load config for server: {ServerName}", serverName);
            return null;
        }
    }

    public ArmaServer GenerateDefaultConfig(string serverName, string installPath)
    {
        return new ArmaServer
        {
            Name = serverName,
            InstallPath = installPath,
            ConfigPath = Path.Combine(installPath, "server.cfg"),
            Port = 2302,
            MaxPlayers = 64,
            Password = "",
            AdminPassword = "admin123"
        };
    }

    private async Task GenerateServerCfgAsync(ArmaServer server)
    {
        var serverCfg = $@"// Server Config for {server.Name}
// Generated by ArmaServerManager on {DateTime.Now:yyyy-MM-dd HH:mm:ss}

// GLOBAL SETTINGS
hostname = ""{server.Name}"";
password = ""{server.Password}"";
passwordAdmin = ""{server.AdminPassword}"";
maxPlayers = {server.MaxPlayers};

// WELCOME MESSAGE
motd[] = {{
    ""Welcome to {server.Name}"",
    ""Enjoy your stay!""
}};

// ADMIN SETTINGS
admins[] = {{}};

// HEADLESS CLIENT
headlessClients[] = {{""127.0.0.1""}};
localClient[] = {{""127.0.0.1""}};

// SECURITY
verifySignatures = 2;
kickDuplicate = 1;
allowedFilePatching = 0;
allowedLoadFileExtensions[] = {{""hpp"",""sqs"",""sqf"",""fsm"",""cpp"",""paa"",""txt"",""xml"",""inc"",""ext"",""sqm"",""ods"",""fxy"",""lip"",""csv"",""kb"",""bik"",""bikb"",""html"",""htm"",""biedi""}};
allowedPreprocessFileExtensions[] = {{""hpp"",""sqs"",""sqf"",""fsm"",""cpp"",""paa"",""txt"",""xml"",""inc"",""ext"",""sqm"",""ods"",""fxy"",""lip"",""csv"",""kb"",""bik"",""bikb"",""html"",""htm"",""biedi""}};
allowedHTMLLoadExtensions[] = {{""htm"",""html"",""xml"",""txt""}};

// PERFORMANCE
MinBandwidth = 131072;
MaxBandwidth = 2147483647;
MaxMsgSend = 256;
MaxSizeGuaranteed = 512;
MaxSizeNonguaranteed = 256;
MinErrorToSend = 0.001;
MinErrorToSendNear = 0.01;

// LOGGING
timeStampFormat = ""short"";
logFile = ""server_console.log"";

// MISSIONS
class Missions
{{
    class Mission1
    {{
        template = ""Altis"";
        difficulty = ""regular"";
    }};
}};";

        if (!string.IsNullOrEmpty(server.InstallPath))
        {
            var cfgPath = Path.Combine(server.InstallPath, "server.cfg");
            Directory.CreateDirectory(Path.GetDirectoryName(cfgPath)!);
            await File.WriteAllTextAsync(cfgPath, serverCfg).ConfigureAwait(false);
        }
    }

    public void SaveConfig(ArmaServer server) => _ = Task.Run(async () => await SaveConfigAsync(server).ConfigureAwait(false));
}